---
- hosts: horses
  user: ubuntu
  become: yes
  tasks:
    - name: change hostname
      hostname:
        name: "MYLOVELYWWW"
    - name: add hostname to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "1.1.1.1     MYLOVELYWWW.ancl.org MYLOVELYWWW"
